import { useInterval } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import About from "./components/About";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export default function Home() {
  const bannerRef = useRef();
  const [screen, setScreen] = useState({ width: 0, height: 0 });

  useEffect(() => {
    setScreen({
      width: window.innerWidth,
      height: window.innerHeight,
    });
  }, []);

  const scroll = () => {
    if (bannerRef.current.scrollLeft == screen.width * 3) {
      bannerRef.current.scrollLeft = 0;
      return;
    }
    bannerRef.current.scrollLeft += screen.width;
  };

  useInterval(() => {
    scroll();
  }, 5000);

  return (
    <>
      <Head>
        <title>Início</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="">
        <Navbar />
        <div
          className="w-full h-max flex overflow-x-hidden relative scroll-smooth"
          ref={bannerRef}
        >
          <div className="w-[100vw] relative shrink-0" style={{ height: screen.width / 2.7 }}>
            <Image src="/banners/1.png" alt="1" layout="fill" />
          </div>
          <div className="w-[100vw] relative shrink-0">
            <Image src="/banners/2.png" alt="2" layout="fill" />
          </div>
          <div className="w-[100vw] relative shrink-0">
            <Image src="/banners/3.png" alt="3" layout="fill" />
          </div>
          <div className="w-[100vw] relative shrink-0">
            <Image src="/banners/4.png" alt="4" layout="fill" />
          </div>
        </div>
        <About />
        <Footer />
      </div>
    </>
  );
}
